import os
import razorpay

RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")

print("RAZORPAY_KEY_ID:", RAZORPAY_KEY_ID)
print("RAZORPAY_KEY_SECRET:", RAZORPAY_KEY_SECRET)

client = razorpay.Client(auth=(RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET))